--1
SELECT ASMENSKODAS, VARDAS, PAVARDE FROM DARBUOTOJAS
where GIMIMOMETAI = '1988-07-20'
--2
SELECT * FROM DARBUOTOJAS
where GIMIMOMETAI <= '1988-07-29'
--3
SELECT DIRBANUO, GIMIMOMETAI FROM DARBUOTOJAS
where DIRBANUO >= '2009-10-30' and DIRBANUO <= '2012-11-11'
--4
SELECT VARDAS, SKYRIUS_PAVADINIMAS, PROJEKTAS_ID FROM DARBUOTOJAS
where PROJEKTAS_ID IN (2,3)
--5
SELECT VARDAS, PAVARDE, ASMENSKODAS FROM DARBUOTOJAS
where VARDAS like '%a'
--6
SELECT * FROM DARBUOTOJAS
where GIMIMOMETAI like '%-12'
--7
SELECT * FROM PROJEKTAS
where PAVADINIMAS like '__u%'
--8
SELECT * FROM DARBUOTOJAS
where PAREIGOS is null
--9
SELECT VARDAS, PAVARDE, DIRBANUO, PAREIGOS FROM DARBUOTOJAS
where DIRBANUO >= '2011-02-12' and PAREIGOS = 'programuotojas'
--10
SELECT VARDAS, PAVARDE, SKYRIUS_PAVADINIMAS, PROJEKTAS_ID FROM DARBUOTOJAS
where SKYRIUS_PAVADINIMAS = 'java' or PROJEKTAS_ID = '1'
--11
SELECT VARDAS FROM DARBUOTOJAS
where VARDAS not like 's%'
--12
SELECT VARDAS, DIRBANUO, GIMIMOMETAI FROM DARBUOTOJAS
where not DIRBANUO >= '2009-10-30' and DIRBANUO <= '2012-11-11'
--13
SELECT VARDAS, PAVARDE, GIMIMOMETAI FROM DARBUOTOJAS
order by GIMIMOMETAI
--14
SELECT VARDAS, PAVARDE, GIMIMOMETAI FROM DARBUOTOJAS
order by GIMIMOMETAI desc
--15
SELECT MAX(PROJEKTAS_ID) AS MaxProjektasID, MIN(PROJEKTAS_ID) AS MinProjektasID
FROM DARBUOTOJAS
--16
SELECT PROJEKTAS_ID, COUNT(VARDAS) AS zmones 
FROM DARBUOTOJAS
GROUP BY PROJEKTAS_ID
--17
SELECT PROJEKTAS_ID as projekto_numeris, 'Programuotojas' AS PAREIGOS, COUNT(*) AS Skaicius
FROM DARBUOTOJAS
WHERE PAREIGOS IN ('Programuotojas', 'Programuotoja')
GROUP BY PROJEKTAS_ID
--18
SELECT PROJEKTAS_ID, 'Darbuotojai' AS PAREIGOS, COUNT(*) AS Skaicius
FROM DARBUOTOJAS
where PROJEKTAS_ID is not null
GROUP BY PROJEKTAS_ID
--18
SELECT PROJEKTAS_ID, PAREIGOS, COUNT(*) AS Skaicius
FROM DARBUOTOJAS
WHERE PROJEKTAS_ID is not null
GROUP BY PROJEKTAS_ID, PAREIGOS 
HAVING COUNT(*) >= 2



