// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Paskaita_3_EntityFramework;

#nullable disable

namespace Paskaita_3_EntityFramework.Migrations.Projektas
{
    [DbContext(typeof(ProjektasContext))]
    [Migration("20240827184940_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Paskaita_3_EntityFramework.Darbuotojas", b =>
                {
                    b.Property<int>("DarbuotojasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DarbuotojasId"));

                    b.Property<string>("AsmensKodas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DirbaNuo")
                        .HasColumnType("datetime2");

                    b.Property<int>("GimimoMetai")
                        .HasColumnType("int");

                    b.Property<string>("Pareigos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pavarde")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjektasId")
                        .HasColumnType("int");

                    b.Property<int>("SkyriusId")
                        .HasColumnType("int");

                    b.Property<string>("Vardas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DarbuotojasId");

                    b.HasIndex("ProjektasId");

                    b.HasIndex("SkyriusId");

                    b.ToTable("Darbuotojai");
                });

            modelBuilder.Entity("Paskaita_3_EntityFramework.Projektas", b =>
                {
                    b.Property<int>("ProjektoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjektoId"));

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Pradzia")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SkyriusId")
                        .HasColumnType("int");

                    b.Property<int>("Trukme")
                        .HasColumnType("int");

                    b.HasKey("ProjektoId");

                    b.HasIndex("SkyriusId");

                    b.ToTable("Projektai");
                });

            modelBuilder.Entity("Paskaita_3_EntityFramework.Skyrius", b =>
                {
                    b.Property<int>("SkyriusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkyriusId"));

                    b.Property<string>("Pavadinimas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VadovoAsmensKodas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkyriusId");

                    b.ToTable("Skyriai");
                });

            modelBuilder.Entity("Paskaita_3_EntityFramework.Darbuotojas", b =>
                {
                    b.HasOne("Paskaita_3_EntityFramework.Projektas", "Projektas")
                        .WithMany("Darbuotojai")
                        .HasForeignKey("ProjektasId");

                    b.HasOne("Paskaita_3_EntityFramework.Skyrius", "Skyrius")
                        .WithMany("Darbuotojai")
                        .HasForeignKey("SkyriusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Projektas");

                    b.Navigation("Skyrius");
                });

            modelBuilder.Entity("Paskaita_3_EntityFramework.Projektas", b =>
                {
                    b.HasOne("Paskaita_3_EntityFramework.Skyrius", null)
                        .WithMany("Projektai")
                        .HasForeignKey("SkyriusId");
                });

            modelBuilder.Entity("Paskaita_3_EntityFramework.Projektas", b =>
                {
                    b.Navigation("Darbuotojai");
                });

            modelBuilder.Entity("Paskaita_3_EntityFramework.Skyrius", b =>
                {
                    b.Navigation("Darbuotojai");

                    b.Navigation("Projektai");
                });
#pragma warning restore 612, 618
        }
    }
}
